name: 'document_intelligence'
version: '1.0.0'
config-version: 2

profile: 'document_intelligence'

model-paths: ["models"]

models:
  document_intelligence:
    staging:
      +materialized: view
    marts:
      +materialized: table